from enum import Enum


class ErrorType(str, Enum):
    UNDERSTANDING_ERROR = "UNDERSTANDING_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    SAFETY_BLOCK = "SAFETY_BLOCK"
    EXECUTOR_ERROR = "EXECUTOR_ERROR"
    TOOL_RUNTIME_ERROR = "TOOL_RUNTIME_ERROR"
