from enum import Enum


class TaskState(str, Enum):
    RECEIVED = "RECEIVED"
    PARSED_BY_RULE = "PARSED_BY_RULE"
    OPTIONAL_LLM_ENRICHED = "OPTIONAL_LLM_ENRICHED"
    NORMALIZED = "NORMALIZED"
    VALIDATED = "VALIDATED"
    SAFETY_CHECKED = "SAFETY_CHECKED"
    DISPATCHED = "DISPATCHED"
    EXECUTOR_RUNNING = "EXECUTOR_RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    DRY_RUN_COMPLETED = "DRY_RUN_COMPLETED"
