"""Board baseline tooling for the formal mainline."""

from jetarm_agent.baseline.audit import BoardEnvironmentSnapshot, collect_board_environment, render_markdown_report
from jetarm_agent.baseline.board_session import (
    BoardActionResult,
    BoardActionStatus,
    BoardSessionAction,
    BoardSessionManifest,
    BoardSessionMode,
    BoardSessionResult,
    PickPlaceFailureStage,
    build_board_session_manifest,
    cli_main as board_session_cli_main,
    initialize_board_session_result,
    record_board_action_result,
    render_board_session_result_markdown,
    render_board_session_runbook,
)
from jetarm_agent.baseline.control_inventory import (
    ControlBoundaryClassification,
    ControlEndpoint,
    ControlEndpointKind,
    ControlInventorySnapshot,
    ControlRiskLevel,
    ControlTier,
    ControlValidationResult,
)
from jetarm_agent.baseline.control_probe import collect_control_inventory, render_control_markdown_report
from jetarm_agent.baseline.supervised_validation import (
    SupervisedValidationSpec,
    SupervisedValidationStep,
    ValidatedActionName,
    ValidationEvidenceBundle,
    ValidationOutcome,
    ValidationStatus,
    build_supervised_validation_specs,
    build_validation_outcomes,
    cli_main,
    render_supervised_validation_protocol,
)

__all__ = [
    "BoardEnvironmentSnapshot",
    "BoardActionResult",
    "BoardActionStatus",
    "BoardSessionAction",
    "BoardSessionManifest",
    "BoardSessionMode",
    "BoardSessionResult",
    "ControlBoundaryClassification",
    "ControlEndpoint",
    "ControlEndpointKind",
    "ControlInventorySnapshot",
    "ControlRiskLevel",
    "ControlTier",
    "ControlValidationResult",
    "PickPlaceFailureStage",
    "board_session_cli_main",
    "build_board_session_manifest",
    "collect_board_environment",
    "collect_control_inventory",
    "initialize_board_session_result",
    "record_board_action_result",
    "render_control_markdown_report",
    "render_board_session_result_markdown",
    "render_board_session_runbook",
    "render_markdown_report",
    "SupervisedValidationSpec",
    "SupervisedValidationStep",
    "ValidatedActionName",
    "ValidationEvidenceBundle",
    "ValidationOutcome",
    "ValidationStatus",
    "build_supervised_validation_specs",
    "build_validation_outcomes",
    "cli_main",
    "render_supervised_validation_protocol",
]
